name: required-reviews
description: Checks the required reviewers have approved a PR.
author: theoremlp
inputs:
  github-token:
    required: true
    description: A valid GitHub token
  config-ref:
    required: true
    default: ""
    description: Load the .github/reviewers.json config from this ref. Can typically set to `github.base_ref`. When empty, the default branch will be used.
runs:
  using: "node16"
  main: "dist/index.js"
